### ISSUE TITLE
Plan - Time for Internal Workshops

### ISSUE THREAD

**Issue by paulpounendis** [adelaideblockchain/education#3]
We are looking to do start workshops Wednesday the 16th of May, continuing fortnightly, completing 2-3 before end of semester. Does this work for everyone? If you have any input please don't hesitate!

**Comment by JJ11teen** [comment]
What time on Wednesdays? Do we want to have it at the same time each time? Do we know who's up for the third one?

**Comment by paulpounendis** [comment]
I think we should have it the same time. I'd say probably 510pm. The competitive programming club do there's 510pm. We can record it so others who can't make it can come. Third one I don't know yet. If we do it fortnightly it might be too close to exams. But out timetable, we will have Wednesday 16th, 30th, then june 14th, where june 14th is smack back in exams, so probably only 2. That will still be sufficient.

**Comment by ivanzinho09** [comment]
Within the coming break, are we wanting to focus mainly on creating workshops/bootcamp/internal learning or all of them? 
We should likely plan out a schedule in order to keep track of what/when/where and who will be participating!

**Comment by JJ11teen** [comment]
A schedule is an excellent idea! This issue and #4 should probably be retitled to focus on scheduling internal and external workshops respectively

**Comment by ivanzinho09** [comment]
Better definition of what we mean by workshops and boot camps would also help when developing material!!! Should workshops be more lecture focused/spaced out and having some coding at the end?
Will boot camps be more of an incubator/accelerated course?

**Comment by JJ11teen** [comment]
I have been using them interchangeably, but yes if they are different they should be better defined

**Comment by paulpounendis** [comment]
We need to create an internal and external timetable, and then further detail deliverables and designate delegation. Both are extremely important. Schedule for events also really important.

**Comment by ivanzinho09** [comment]
I feel this will also go hand in hand with task allocation. Good thing we are going to try and tackle that in the first week of July!

**Comment by JJ11teen** [comment]
Created #5 to track discussion about workshop vs bootcamp terminology
