### ISSUE TITLE
Organising Boot Camp

### ISSUE THREAD

**Issue by ivanzinho09** [adelaideblockchain/education#4]
We need to start thinking about boot camps, their structure, dates and their time lines.
Be mindful that a lot of information will need to be processed by members and this upcoming holiday would be ideal.

**Comment by JJ11teen** [comment]
Is this different to external workshops? If not I suggest renaming this issue to track the scheduling of external workshops.

**Comment by paulpounendis** [comment]
As an update, we should establish this issue the start of developing an intensive day workshop for the first Saturday of August. I think that what would make sense is make the first 2-3 hours is general theory and idea based exercise to engage people with the concepts. I'll include an IDEAS.md for the bootcamp
